---
- hosts: localhost
  gather_facts: false
  name: Basic Connectivity Test
  vars_files:
    - test_vars.yml
  vars_prompt:
    - name: "netapp_password"
      prompt: "Enter the NetApp Admin Password"
      private: yes
  collections:
    - netapp.ontap
  tasks:
  - name: Connectivity Test & Display ONTAP_info - All
    netapp.ontap.na_ontap_info:
      state: info
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
    register: ontap_info
  - debug:
      msg: "{{ ontap_info.ontap_info }}"

  - name: Get NetApp version as Vserver admin
    na_ontap_info:
      state: info
      vserver: trident_svm
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
