---
- hosts: localhost
  gather_facts: false
  vars_files:
    - test_vars.yml
  vars_prompt:
    - name: "netapp_password"
      prompt: "Enter the NetApp Admin Password"
      private: yes
  collections:
    - netapp.ontap
  tasks:
  - name: test
    na_ontap_info:
      state: info
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
