---
- hosts: all
  name: Example of rebooting a linux system based on kernel updates installed


    - name: Check if a reboot is needed on Ubuntu/Debian
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no

    - name: Reboot if kernel update/installed
      reboot:
        msg: "Reboot initiated by Ansible for kernel update"
        connect_timeou: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_requried_file.exists
