---
- hosts: localhost
  gather_facts: true
  vars_files:
    - ['globals.yml' ]
  vars:
    input: &input
      hostname: '{{ netapp_hostname }}'
      username: '{{ netapp_username }}'
      password: '{{ netapp_password }}'
      https: true
      validate_certs: false
  tasks:
    - name: Get Ontap Facts
      na_ontap_info:
         state: info
         <<: *input
      register: netapp
    - import_role:
        name: na_ontap_cluster_config
      vars:
        <<: *input
