# Varibles for ONTAP setup & config
cluster: sandbox
cluster_aggr: "{{ cluster | replace('-','_') }}"  # For use with vserver role, Remove '-'s and replace with '_'s
cluster_mgmt: 192.168.7.200
node1:
  node_mgmt_ip: 192.168.7.201
  icl: 192.168.7.202
  vs0: 192.168.7.205
node2:
  node_mgmt_ip: 192.168.7.203
  icl: 192.168.7.204
  vs0: 192.168.7.206

# Authentification Defaults
netapp_hostname: "{{ cluster_mgmt }}"
netapp_username: admin
netapp_password: netapp1234     # Comment out to use vars_prompt
validate_certs: false           # Set the default

# SVM configuration
svm: ontap-vs01

###
# Module-Based:  SNMP Configuration varibles
###

# SNMP Community
snmp_com: 'communityName'

# SNMP Location
snmp_loc: 'VSIM'

# SNMP CMD
set_loc: 'system snmp location -location "{{ snmp_loc }}"'

# SNMP Traphost
snmp_thost: '192.168.7.122'


# firewall ocnfiguration
# fw_allow_list: [10.16.0.0/16,192.168.7.0/24]
fw_allow_list: [192.168.7.122/32]
